{
 "title": "SSH Session - Muazzam",
 "description": "Muazzam",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Current SSH Session",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ssh_num_sessions{remote_ip!=\"-\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 4, "y": 0 },
   "targets": [
    { "expr": "sum(ssh_num_sessions)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "SSH Session",
   "type": "status-history",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "ssh_num_sessions{job=\"prometheus-ssh-exporter\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "List of current Session (Remote IP)",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by(instance) (ssh_num_sessions)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Current SSH Session",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 7 },
   "targets": [
    {
     "expr": "ssh_num_sessions{remote_ip!=\"-\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "List of current Session (Local)",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by(remote_ip) (ssh_num_sessions)",
     "legendFormat": "{{remote_ip}}"
    }
   ]
  }
 ]
}